In [2]:
# https://pandas.pydata.org/
import pandas

# https://github.com/Data-Centric-AI-Community/fg-data-profiling
import data_profiling
from data_profiling import ProfileReport

# Introducción

[https://www.cosmos.esa.int/web/hipparcos/home](https://www.cosmos.esa.int/web/hipparcos/home)

[https://sci.esa.int/web/hipparcos/](https://sci.esa.int/web/hipparcos/)

In [6]:
# https://cdsarc.cds.unistra.fr/viz-bin/cat/I/239#
# https://cdsarc.cds.unistra.fr/viz-bin/ReadMe/I/239?format=html&tex=true
# https://vizier.cds.unistra.fr/viz-bin/VizieR-4
# http://cdsportal.u-strasbg.fr/my-data/

#file = "data_raw/vizier_I_239_hip_main_20260720.csv"
file = "data_raw/vizier_I_239_hip_main_20260720.tsv"

# leer .tsv
df = pandas.read_csv(
    file,              # nombre y ruta del archivo
    sep='\t',          # símbolo de separación de columnas    
    nrows = 118218,    # número de filas que se leerán
    index_col = 'HIP', # nombre de la columna índice
)

# dataframe
print( type(df) )

df

<class 'pandas.core.frame.DataFrame'>

,recno,Proxy,RAhms,DEdms,Vmag,VarFlag,r_Vmag,RAICRS,DEICRS,AstroRef,...,BD,CoD,CPD,(V-I)red,SpType,r_SpType,HIPep,Erratum,_RA.icrs,_DE.icrs
HIP,,,,,,,,,,,,,,,,,,,,,
1,1,NaN,00 00 00.22,+01 05 20.4,9.10,NaN,H,0.000912,1.089013,NaN,...,B+00 5077,NaN,NaN,0.66,F5,S,HIPep,Erratum,0.000899,1.089009
2,2,NaN,00 00 00.91,-19 29 55.8,9.27,NaN,G,0.003797,-19.498837,+,...,B-20 6688,NaN,NaN,1.04,K3V,4,HIPep,Erratum,0.004265,-19.498840
3,3,NaN,00 00 01.20,+38 51 33.4,6.61,NaN,G,0.005008,38.859286,NaN,...,B+38 5108,NaN,NaN,0.00,B9,S,HIPep,Erratum,0.005024,38.859279
4,4,NaN,00 00 02.01,-51 53 36.8,8.06,NaN,H,0.008382,-51.893546,NaN,...,NaN,NaN,P-52 12237,0.43,F0V,2,HIPep,Erratum,0.008629,-51.893546
5,5,NaN,00 00 02.39,-40 35 28.4,8.55,NaN,H,0.009965,-40.591224,NaN,...,NaN,C-41 15372,P-41 9991,0.95,G8III,2,HIPep,Erratum,0.009973,-40.591202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118318,118214,NaN,23 59 51.30,+11 40 25.4,6.99,1.0,H,359.963744,11.673709,NaN,...,B+10 5018,NaN,NaN,1.56,K2,S,HIPep,Erratum,359.963738,11.673714
118319,118215,NaN,23 59 53.74,-22 25 41.4,8.23,NaN,G,359.973913,-22.428180,NaN,...,NaN,C-23 18108,P-23 8366,0.70,G2V,4,HIPep,Erratum,359.974304,-22.428113
118320,118216,NaN,23 59 54.25,+05 57 23.9,7.59,NaN,H,359.976057,5.956638,NaN,...,B+05 5245,NaN,NaN,0.98,K0,S,HIPep,Erratum,359.976109,5.956552
118321,118217,NaN,23 59 54.78,-64 22 21.3,9.20,NaN,G,359.978239,-64.372572,NaN,...,NaN,C-65 2958,P-65 4188,0.75,G5V,1,HIPep,Erratum,359.979458,-64.372313
118322,118218,NaN,23 59 54.91,-65 34 37.5,4.49,NaN,H,359.978792,-65.577078,NaN,...,NaN,NaN,P-66 3819,-0.04,B9IV,X,HIPep,Erratum,359.979078,-65.577132

## Dataset Profiling Report

In [6]:
#data_profiling.ProfileReport(df)
#ProfileReport(df)
profile = ProfileReport(df, title="Profiling Report")
#profile

In [7]:
file_report = 'profiles/HIP_profile_short.html'
#profile.to_file(output_file = file_report)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|                                                                                                                                                     | 0/80 [00:00<?, ?it/s]
  1%|█▊                                                                                                                                           | 1/80 [00:00<00:33,  2.38it/s]
  2%|███▌                                                                                                                                         | 2/80 [00:01<00:27,  2.84it/s]
  4%|█████▎                                                                                                                                       | 3/80 [00:01<00:33,  2.31it/s]
 34%|███████████████████████████████████████████████▎                                                                                            | 27/80 [00:01<00:01, 28.61it/s]
 40%|████████████████████████████████████████████████████████                                                                                    | 32/80 [00:01<00:01, 29.35it/s]
 45%|███████████████████████████████████████████████████████████████                                                                             | 36/80 [00:01<00:01, 28.55it/s]
 50%|██████████████████████████████████████████████████████████████████████                                                                      | 40/80 [00:01<00:01, 28.42it/s]
 55%|█████████████████████████████████████████████████████████████████████████████                                                               | 44/80 [00:02<00:01, 20.86it/s]
 59%|██████████████████████████████████████████████████████████████████████████████████▎                                                         | 47/80 [00:03<00:03, 10.98it/s]
 61%|█████████████████████████████████████████████████████████████████████████████████████▊                                                      | 49/80 [00:03<00:02, 10.97it/s]
 64%|█████████████████████████████████████████████████████████████████████████████████████████▎                                                  | 51/80 [00:03<00:02, 10.64it/s]
 66%|████████████████████████████████████████████████████████████████████████████████████████████▊                                               | 53/80 [00:03<00:02, 10.45it/s]
 69%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                           | 55/80 [00:04<00:02, 10.32it/s]
 71%|███████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 57/80 [00:04<00:02,  8.14it/s]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌                                      | 58/80 [00:04<00:03,  5.75it/s]
 74%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                                    | 59/80 [00:04<00:03,  6.00it/s]
 75%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                                   | 60/80 [00:05<00:03,  6.17it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [00:05<00:00, 15.16it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

## columns

In [8]:
df.columns

Index(['recno', 'Proxy', 'RAhms', 'DEdms', 'Vmag', 'VarFlag', 'r_Vmag',
       'RAICRS', 'DEICRS', 'AstroRef', 'Plx', 'pmRA', 'pmDE', 'e_RAICRS',
       'e_DEICRS', 'e_Plx', 'e_pmRA', 'e_pmDE', 'DE:RA', 'Plx:RA', 'Plx:DE',
       'pmRA:RA', 'pmRA:DE', 'pmRA:Plx', 'pmDE:RA', 'pmDE:DE', 'pmDE:Plx',
       'pmDE:pmRA', 'F1', 'F2', 'BTmag', 'e_BTmag', 'VTmag', 'e_VTmag',
       'm_BTmag', 'B-V', 'e_B-V', 'r_B-V', 'V-I', 'e_V-I', 'r_V-I', 'CombMag',
       'Hpmag', 'e_Hpmag', 'Hpscat', 'o_Hpmag', 'm_Hpmag', 'Hpmax', 'HPmin',
       'Period', 'HvarType', 'moreVar', 'morePhoto', 'CCDM', 'n_CCDM', 'Nsys',
       'Ncomp', 'MultFlag', 'Source', 'Qual', 'm_HIP', 'theta', 'rho', 'e_rho',
       'dHp', 'e_dHp', 'Survey', 'Chart', 'Notes', 'HD', 'BD', 'CoD', 'CPD',
       '(V-I)red', 'SpType', 'r_SpType', 'HIPep', 'Erratum', '_RA.icrs',
       '_DE.icrs'],
      dtype='object')

## index

In [9]:
df.index

Index([     1,      2,      3,      4,      5,      6,      7,      8,      9,
           10,
       ...
       118313, 118314, 118315, 118316, 118317, 118318, 118319, 118320, 118321,
       118322],
      dtype='int64', name='HIP', length=118218)

## values

In [10]:
df.values

array([[1, nan, '00 00 00.22', ..., 'Erratum', 0.00089921, 1.08900875],
       [2, nan, '00 00 00.91', ..., 'Erratum', 0.00426461, -19.49883971],
       [3, nan, '00 00 01.20', ..., 'Erratum', 0.00502431, 38.85927901],
       ...,
       [118216, nan, '23 59 54.25', ..., 'Erratum', 359.97610859,
        5.95655216],
       [118217, nan, '23 59 54.78', ..., 'Erratum', 359.97945829,
        -64.37231344],
       [118218, nan, '23 59 54.91', ..., 'Erratum', 359.97907782,
        -65.57713201]], shape=(118218, 80), dtype=object)

## info

In [11]:
# General info about features
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118218 entries, 1 to 118322
Data columns (total 80 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   recno      118218 non-null  int64
 1   Proxy      10925 non-null   object
 2   RAhms      118218 non-null  object
 3   DEdms      118218 non-null  object
 4   Vmag       118217 non-null  float64
 5   VarFlag    11562 non-null   float64
 6   r_Vmag     118217 non-null  object
 7   RAICRS     117955 non-null  float64
 8   DEICRS     117955 non-null  float64
 9   AstroRef   13734 non-null   object
 10  Plx        117955 non-null  float64
 11  pmRA       117955 non-null  float64
 12  pmDE       117955 non-null  float64
 13  e_RAICRS   117955 non-null  float64
 14  e_DEICRS   117955 non-null  float64
 15  e_Plx      117955 non-null  float64
 16  e_pmRA     117955 non-null  float64
 17  e_pmDE     117955 non-null  float64
 18  DE:RA      117955 non-null  float64
 19  Plx:RA     117955 non-null  float64
 20  Plx:DE     117955 non-null  float64
 21  pmRA:RA    117955 non-null  float64
 22  pmRA:DE    117955 non-null  float64
 23  pmRA:Plx   117955 non-null  float64
 24  pmDE:RA    117955 non-null  float64
 25  pmDE:DE    117955 non-null  float64
 26  pmDE:Plx   117955 non-null  float64
 27  pmDE:pmRA  117955 non-null  float64
 28  F1         117955 non-null  float64
 29  F2         116392 non-null  float64
 30  BTmag      114820 non-null  float64
 31  e_BTmag    114820 non-null  float64
 32  VTmag      114879 non-null  float64
 33  e_VTmag    114879 non-null  float64
 34  m_BTmag    12796 non-null   object
 35  B-V        116937 non-null  float64
 36  e_B-V      116937 non-null  float64
 37  r_B-V      116937 non-null  object
 38  V-I        116943 non-null  float64
 39  e_V-I      116943 non-null  float64
 40  r_V-I      118218 non-null  object
 41  CombMag    10783 non-null   object
 42  Hpmag      118204 non-null  float64
 43  e_Hpmag    118204 non-null  float64
 44  Hpscat     117247 non-null  float64
 45  o_Hpmag    117247 non-null  float64
 46  m_Hpmag    13211 non-null   object
 47  Hpmax      117247 non-null  float64
 48  HPmin      117247 non-null  float64
 49  Period     2541 non-null    float64
 50  HvarType   71622 non-null   object
 51  moreVar    8254 non-null    float64
 52  morePhoto  3581 non-null    object
 53  CCDM       19393 non-null   object
 54  n_CCDM     19393 non-null   object
 55  Nsys       19393 non-null   float64
 56  Ncomp      117955 non-null  float64
 57  MultFlag   17917 non-null   object
 58  Source     3236 non-null    object
 59  Qual       20835 non-null   object
 60  m_HIP      11101 non-null   object
 61  theta      11101 non-null   float64
 62  rho        11101 non-null   float64
 63  e_rho      11101 non-null   float64
 64  dHp        11101 non-null   float64
 65  e_dHp      11101 non-null   float64
 66  Survey     52045 non-null   object
 67  Chart      11653 non-null   object
 68  Notes      4178 non-null    object
 69  HD         98880 non-null   float64
 70  BD         73160 non-null   object
 71  CoD        27880 non-null   object
 72  CPD        40250 non-null   object
 73  (V-I)red   118218 non-null  float64
 74  SpType     115184 non-null  object
 75  r_SpType   115184 non-null  object
 76  HIPep      118218 non-null  object
 77  Erratum    118218 non-null  object
 78  _RA.icrs   117955 non-null  float64
 79  _DE.icrs   117955 non-null  float64
dtypes: float64(51), int64(1), object(28)
memory usage: 77.1+ MB

## memory_usage

In [12]:
df.memory_usage()

Index       5172856
recno        945744
Proxy        945744
RAhms        945744
DEdms        945744
             ...
r_SpType     945744
HIPep        945744
Erratum      945744
_RA.icrs     945744
_DE.icrs     945744
Length: 81, dtype: int64

## shape

In [13]:
df.shape

(118218, 80)

## head

In [14]:
df.head()

,recno,Proxy,RAhms,DEdms,Vmag,VarFlag,r_Vmag,RAICRS,DEICRS,AstroRef,...,BD,CoD,CPD,(V-I)red,SpType,r_SpType,HIPep,Erratum,_RA.icrs,_DE.icrs
HIP,,,,,,,,,,,,,,,,,,,,,
1,1,NaN,00 00 00.22,+01 05 20.4,9.10,NaN,H,0.000912,1.089013,NaN,...,B+00 5077,NaN,NaN,0.66,F5,S,HIPep,Erratum,0.000899,1.089009
2,2,NaN,00 00 00.91,-19 29 55.8,9.27,NaN,G,0.003797,-19.498837,+,...,B-20 6688,NaN,NaN,1.04,K3V,4,HIPep,Erratum,0.004265,-19.498840
3,3,NaN,00 00 01.20,+38 51 33.4,6.61,NaN,G,0.005008,38.859286,NaN,...,B+38 5108,NaN,NaN,0.00,B9,S,HIPep,Erratum,0.005024,38.859279
4,4,NaN,00 00 02.01,-51 53 36.8,8.06,NaN,H,0.008382,-51.893546,NaN,...,NaN,NaN,P-52 12237,0.43,F0V,2,HIPep,Erratum,0.008629,-51.893546
5,5,NaN,00 00 02.39,-40 35 28.4,8.55,NaN,H,0.009965,-40.591224,NaN,...,NaN,C-41 15372,P-41 9991,0.95,G8III,2,HIPep,Erratum,0.009973,-40.591202

## tail

In [15]:
df.tail()

,recno,Proxy,RAhms,DEdms,Vmag,VarFlag,r_Vmag,RAICRS,DEICRS,AstroRef,...,BD,CoD,CPD,(V-I)red,SpType,r_SpType,HIPep,Erratum,_RA.icrs,_DE.icrs
HIP,,,,,,,,,,,,,,,,,,,,,
118318,118214,NaN,23 59 51.30,+11 40 25.4,6.99,1.0,H,359.963744,11.673709,NaN,...,B+10 5018,NaN,NaN,1.56,K2,S,HIPep,Erratum,359.963738,11.673714
118319,118215,NaN,23 59 53.74,-22 25 41.4,8.23,NaN,G,359.973913,-22.428180,NaN,...,NaN,C-23 18108,P-23 8366,0.70,G2V,4,HIPep,Erratum,359.974304,-22.428113
118320,118216,NaN,23 59 54.25,+05 57 23.9,7.59,NaN,H,359.976057,5.956638,NaN,...,B+05 5245,NaN,NaN,0.98,K0,S,HIPep,Erratum,359.976109,5.956552
118321,118217,NaN,23 59 54.78,-64 22 21.3,9.20,NaN,G,359.978239,-64.372572,NaN,...,NaN,C-65 2958,P-65 4188,0.75,G5V,1,HIPep,Erratum,359.979458,-64.372313
118322,118218,NaN,23 59 54.91,-65 34 37.5,4.49,NaN,H,359.978792,-65.577078,NaN,...,NaN,NaN,P-66 3819,-0.04,B9IV,X,HIPep,Erratum,359.979078,-65.577132