In [1]:
import pandas

# Limpieza

In [2]:
# https://vizier.cds.unistra.fr/viz-bin/VizieR-4
# http://cdsportal.u-strasbg.fr/my-data/

file = "data_raw/vizier_I_239_hip_main_20260720.tsv"

# leer .tsv
df = pandas.read_csv(
    file,              # nombre y ruta del archivo
    sep = '\t',        # símbolo de separación de columnas
    nrows = 118218,    # número de filas que se leerán
    index_col = 'HIP', # nombre de la columna índice
)

# dataframe
print( type(df) )

df

<class 'pandas.core.frame.DataFrame'>

,recno,Proxy,RAhms,DEdms,Vmag,VarFlag,r_Vmag,RAICRS,DEICRS,AstroRef,...,BD,CoD,CPD,(V-I)red,SpType,r_SpType,HIPep,Erratum,_RA.icrs,_DE.icrs
HIP,,,,,,,,,,,,,,,,,,,,,
1,1,NaN,00 00 00.22,+01 05 20.4,9.10,NaN,H,0.000912,1.089013,NaN,...,B+00 5077,NaN,NaN,0.66,F5,S,HIPep,Erratum,0.000899,1.089009
2,2,NaN,00 00 00.91,-19 29 55.8,9.27,NaN,G,0.003797,-19.498837,+,...,B-20 6688,NaN,NaN,1.04,K3V,4,HIPep,Erratum,0.004265,-19.498840
3,3,NaN,00 00 01.20,+38 51 33.4,6.61,NaN,G,0.005008,38.859286,NaN,...,B+38 5108,NaN,NaN,0.00,B9,S,HIPep,Erratum,0.005024,38.859279
4,4,NaN,00 00 02.01,-51 53 36.8,8.06,NaN,H,0.008382,-51.893546,NaN,...,NaN,NaN,P-52 12237,0.43,F0V,2,HIPep,Erratum,0.008629,-51.893546
5,5,NaN,00 00 02.39,-40 35 28.4,8.55,NaN,H,0.009965,-40.591224,NaN,...,NaN,C-41 15372,P-41 9991,0.95,G8III,2,HIPep,Erratum,0.009973,-40.591202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118318,118214,NaN,23 59 51.30,+11 40 25.4,6.99,1.0,H,359.963744,11.673709,NaN,...,B+10 5018,NaN,NaN,1.56,K2,S,HIPep,Erratum,359.963738,11.673714
118319,118215,NaN,23 59 53.74,-22 25 41.4,8.23,NaN,G,359.973913,-22.428180,NaN,...,NaN,C-23 18108,P-23 8366,0.70,G2V,4,HIPep,Erratum,359.974304,-22.428113
118320,118216,NaN,23 59 54.25,+05 57 23.9,7.59,NaN,H,359.976057,5.956638,NaN,...,B+05 5245,NaN,NaN,0.98,K0,S,HIPep,Erratum,359.976109,5.956552
118321,118217,NaN,23 59 54.78,-64 22 21.3,9.20,NaN,G,359.978239,-64.372572,NaN,...,NaN,C-65 2958,P-65 4188,0.75,G5V,1,HIPep,Erratum,359.979458,-64.372313
118322,118218,NaN,23 59 54.91,-65 34 37.5,4.49,NaN,H,359.978792,-65.577078,NaN,...,NaN,NaN,P-66 3819,-0.04,B9IV,X,HIPep,Erratum,359.979078,-65.577132

## Elementos con valores en null o NaN

In [3]:
df.isnull().sum()

recno            0
Proxy       107293
RAhms            0
DEdms            0
Vmag             1
             ...
r_SpType      3034
HIPep            0
Erratum          0
_RA.icrs       263
_DE.icrs       263
Length: 80, dtype: int64

### 1 registro igual a NaN en la columna de magnitud Vmag

In [4]:
df.loc[ df['Vmag'].isna() ]

,recno,Proxy,RAhms,DEdms,Vmag,VarFlag,r_Vmag,RAICRS,DEICRS,AstroRef,...,BD,CoD,CPD,(V-I)red,SpType,r_SpType,HIPep,Erratum,_RA.icrs,_DE.icrs
HIP,,,,,,,,,,,,,,,,,,,,,
120412,25190,NaN,05 23 33.71,-60 55 29.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-0.3,NaN,NaN,HIPep,Erratum,NaN,NaN

### 263 registros con valor NaN en la columna de paralaje Plx, RAICRS y DEICRS

In [5]:
df[ ~df['Plx'].notnull() ]

,recno,Proxy,RAhms,DEdms,Vmag,VarFlag,r_Vmag,RAICRS,DEICRS,AstroRef,...,BD,CoD,CPD,(V-I)red,SpType,r_SpType,HIPep,Erratum,_RA.icrs,_DE.icrs
HIP,,,,,,,,,,,,,,,,,,,,,
421,421,NaN,00 05 08.11,+45 13 32.4,8.83,NaN,H,NaN,NaN,NaN,...,NaN,NaN,NaN,0.73,NaN,NaN,HIPep,Erratum,NaN,NaN
1902,1900,NaN,00 24 02.87,-72 05 43.3,8.88,NaN,H,NaN,NaN,NaN,...,NaN,NaN,P-72 35,1.18,Ne...,1,HIPep,Erratum,NaN,NaN
2189,2187,NaN,00 27 39.32,-16 24 45.4,7.82,NaN,H,NaN,NaN,NaN,...,NaN,NaN,NaN,0.72,NaN,NaN,HIPep,Erratum,NaN,NaN
1338,1337,NaN,00 16 44.87,+41 04 08.7,9.20,2.0,H,NaN,NaN,NaN,...,B+40 43,NaN,NaN,0.87,NaN,NaN,HIPep,Erratum,NaN,NaN
3158,3156,NaN,00 40 09.96,-08 55 53.3,9.59,3.0,G,NaN,NaN,NaN,...,B-09 129,NaN,NaN,0.47,A5,S,HIPep,Erratum,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112856,112756,NaN,22 51 17.25,+29 14 07.1,8.86,NaN,H,NaN,NaN,NaN,...,NaN,NaN,NaN,0.72,NaN,NaN,HIPep,Erratum,NaN,NaN
114349,114248,NaN,23 09 33.66,+00 43 26.4,12.41,NaN,H,NaN,NaN,NaN,...,NaN,NaN,NaN,0.76,G2,S,HIPep,Erratum,NaN,NaN
115125,115024,NaN,23 19 06.37,-13 27 17.0,5.19,NaN,H,NaN,NaN,NaN,...,NaN,NaN,NaN,0.90,K2V,X,HIPep,Erratum,NaN,NaN
115269,115169,NaN,23 20 49.16,-50 18 37.0,8.89,NaN,G,NaN,NaN,NaN,...,NaN,C-50 13947,NaN,0.67,Am,X,HIPep,Erratum,NaN,NaN
117643,117539,NaN,23 51 32.52,+42 05 17.8,9.24,NaN,H,NaN,NaN,NaN,...,NaN,NaN,NaN,0.72,NaN,NaN,HIPep,Erratum,NaN,NaN

### 4196 registros menores a 0 en la columna de Plx

In [6]:
df[df['Plx'] < 0]

,recno,Proxy,RAhms,DEdms,Vmag,VarFlag,r_Vmag,RAICRS,DEICRS,AstroRef,...,BD,CoD,CPD,(V-I)red,SpType,r_SpType,HIPep,Erratum,_RA.icrs,_DE.icrs
HIP,,,,,,,,,,,,,,,,,,,,,
40,41,H,00 00 29.27,+67 13 00.4,10.61,2.0,G,0.121970,67.216791,A,...,B+66 1669,NaN,NaN,0.64,B...,S,HIPep,Erratum,0.121951,67.216784
53,53,NaN,00 00 35.37,-29 15 48.2,10.96,NaN,H,0.147390,-29.263382,NaN,...,NaN,C-29 18916,NaN,0.72,NaN,NaN,HIPep,Erratum,0.147424,-29.263414
59,59,NaN,00 00 41.87,+55 43 20.9,9.09,NaN,H,0.174447,55.722463,NaN,...,B+54 3093,NaN,NaN,1.71,B5,G,HIPep,Erratum,0.174446,55.722460
147,147,NaN,00 01 51.85,+21 01 34.5,8.49,NaN,H,0.466044,21.026249,NaN,...,B+20 5419,NaN,NaN,1.59,K5,S,HIPep,Erratum,0.466060,21.026236
165,165,NaN,00 02 04.74,-22 19 38.9,10.16,NaN,H,0.519745,-22.327471,NaN,...,NaN,C-23 18120,P-23 8372,1.04,Ap...,4,HIPep,Erratum,0.519733,-22.327487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118142,118038,NaN,23 57 49.75,+68 28 28.5,10.84,NaN,H,359.457300,68.474580,NaN,...,B+67 1581,NaN,NaN,0.70,NaN,NaN,HIPep,Erratum,359.457293,68.474575
118174,118070,NaN,23 58 17.98,+61 13 15.8,11.09,2.0,H,359.574917,61.221065,NaN,...,NaN,NaN,NaN,1.21,F8Ibvar,X,HIPep,Erratum,359.574914,61.221060
118202,118098,NaN,23 58 33.65,-29 12 37.3,8.41,NaN,H,359.640200,-29.210352,NaN,...,NaN,C-29 18903,P-29 6890,1.07,K1III,3,HIPep,Erratum,359.640310,-29.210333
118211,118107,NaN,23 58 42.63,-53 49 11.1,9.04,NaN,H,359.677629,-53.819757,NaN,...,NaN,NaN,P-54 10405,1.37,K3/K4,1,HIPep,Erratum,359.677660,-53.819767
118283,118181,NaN,23 59 30.46,-26 31 35.9,8.26,NaN,H,359.876929,-26.526633,B,...,NaN,NaN,NaN,0.39,F0,G,HIPep,Erratum,359.877145,-26.526597

In [7]:
df.loc[ df['Plx'] < 0 ].nunique()

recno       4196
Proxy          2
RAhms       4195
DEdms       4194
Vmag         644
            ...
r_SpType       8
HIPep          1
Erratum        1
_RA.icrs    4196
_DE.icrs    4196
Length: 80, dtype: int64

## Removiendo las malas entradas

In [8]:
# dataframe en donde los valores de Plx sean mayores a 0
# y en Rahms, DEdms y Vmag no sean NaN
# De 118,218 se reduce a 113,710

# remove bad entries and higher error
valid_mask = (
    ( df['Plx'] > 0) &
    
    ( df['Vmag'].notna() )  &
    
    ( df['RAICRS'].notna() ) &
    ( df['DEICRS'].notna() ) &
    ( df['RAhms'].notna() ) &
    ( df['DEdms'].notna() )  
)

df_nan_par_corrected = df[ valid_mask ].copy()

df_nan_par_corrected

,recno,Proxy,RAhms,DEdms,Vmag,VarFlag,r_Vmag,RAICRS,DEICRS,AstroRef,...,BD,CoD,CPD,(V-I)red,SpType,r_SpType,HIPep,Erratum,_RA.icrs,_DE.icrs
HIP,,,,,,,,,,,,,,,,,,,,,
1,1,NaN,00 00 00.22,+01 05 20.4,9.10,NaN,H,0.000912,1.089013,NaN,...,B+00 5077,NaN,NaN,0.66,F5,S,HIPep,Erratum,0.000899,1.089009
2,2,NaN,00 00 00.91,-19 29 55.8,9.27,NaN,G,0.003797,-19.498837,+,...,B-20 6688,NaN,NaN,1.04,K3V,4,HIPep,Erratum,0.004265,-19.498840
3,3,NaN,00 00 01.20,+38 51 33.4,6.61,NaN,G,0.005008,38.859286,NaN,...,B+38 5108,NaN,NaN,0.00,B9,S,HIPep,Erratum,0.005024,38.859279
4,4,NaN,00 00 02.01,-51 53 36.8,8.06,NaN,H,0.008382,-51.893546,NaN,...,NaN,NaN,P-52 12237,0.43,F0V,2,HIPep,Erratum,0.008629,-51.893546
5,5,NaN,00 00 02.39,-40 35 28.4,8.55,NaN,H,0.009965,-40.591224,NaN,...,NaN,C-41 15372,P-41 9991,0.95,G8III,2,HIPep,Erratum,0.009973,-40.591202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118318,118214,NaN,23 59 51.30,+11 40 25.4,6.99,1.0,H,359.963744,11.673709,NaN,...,B+10 5018,NaN,NaN,1.56,K2,S,HIPep,Erratum,359.963738,11.673714
118319,118215,NaN,23 59 53.74,-22 25 41.4,8.23,NaN,G,359.973913,-22.428180,NaN,...,NaN,C-23 18108,P-23 8366,0.70,G2V,4,HIPep,Erratum,359.974304,-22.428113
118320,118216,NaN,23 59 54.25,+05 57 23.9,7.59,NaN,H,359.976057,5.956638,NaN,...,B+05 5245,NaN,NaN,0.98,K0,S,HIPep,Erratum,359.976109,5.956552
118321,118217,NaN,23 59 54.78,-64 22 21.3,9.20,NaN,G,359.978239,-64.372572,NaN,...,NaN,C-65 2958,P-65 4188,0.75,G5V,1,HIPep,Erratum,359.979458,-64.372313
118322,118218,NaN,23 59 54.91,-65 34 37.5,4.49,NaN,H,359.978792,-65.577078,NaN,...,NaN,NaN,P-66 3819,-0.04,B9IV,X,HIPep,Erratum,359.979078,-65.577132

## exportar

In [71]:
# exporta el dataframe a .csv
out_file_csv = "data_clean/vizier_I_239_hip_main_LimpiezaNaNPlx"

#df_nan_par_corrected.to_csv(out_file_csv)

# exporta el dataframe a .tsv
#df_nan_par_corrected.to_csv(out_file_tsv + ".tsv", sep='\t')