In [1]:
from datascience import *
import pandas as pd
import seaborn as sns
import numpy as np
import math

from astropy import units as u
from astropy.time import Time
from astropy.coordinates import SkyCoord

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Loading functions

#### m - M = 5 log d - 5
#### d = 10**((m - M + 5) / 5)
#### M = m + 5 - 5 log d
#### M = m + 5 + 5 log π”

In [4]:
def calculate_abs_mag(app_mag, mas):
    """ Calcular magnitud absoluta
        M = m + 5 + 5 log π
    """
    arcsec = mas/1000
    abs_mag = (math.log(arcsec, 10) * 5) + 5 + app_mag
    return abs_mag

def calculate_distance(app_mag, abs_mag):
    """ Calcular distancia
        m - M = 5 log d - 5 
        d = 10**((m - M + 5) / 5)
    """
    log = (float(app_mag) - float(abs_mag) + 5) / 5
    dist = 10**log
    return dist # parsecs

def distance_modulus(app_mag, abs_mag): # Distance modulus
    """ Calcular módulo distancia
        m - M = 5log * d - 5 
    """    
    d = app_mag - abs_mag
    log = (d + 5) / 5
    dist = 10**log
    
    if d < 0:
        print("The distance is less than 10 pc")
    else:
        print("The distance is less than 10 pc")
        
    return dist # parsecs

def log(arcsec):
    """ Escala logaritmica de base 10
    """
    log = 10**arcsec
    return log

In [ ]:
def calculate_abs_mag(app_mag, mas):
    """ Calcular magnitud absoluta
        M = m + 5 + 5 log π
    """
    arcsec = mas/1000
    abs_mag = (math.log(arcsec, 10) * 5) + 5 + app_mag
    return abs_mag

In [1]:
#### http://docs.astropy.org/en/stable/coordinates/index.html
#### http://cdsarc.u-strasbg.fr/viz-bin/nph-Cat/html?I/239/hip_main.dat.gz
#### http://cdsarc.u-strasbg.fr/viz-bin/cat/I/239
#### https://inferentialthinking.com
#### http://data8.org/datascience/

# Hipparcos Main Catalogue

# Reading data
## 118,218 stars

In [3]:
dat_c = Table.read_table("eric_dat.csv", sep=',')
dat_c.show(5)

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3254: DtypeWarning: Columns (5,44,45) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

# Selecting variables 'HIP', 'RAdeg', 'Dedeg', 'Vmag', 'Plx'

In [5]:
data = dat_c.select(1, 3, 4, 8, 9, 5, 11)
data

HIP  | RAhms       | DEdms       | RAdeg        | DEdeg        | Vmag  | Plx
1    | 00 00 00.22 | +01 05 20.4 | 000.00091185 | +01.08901332 | 9.1   |    3.54
2    | 00 00 00.91 | -19 29 55.8 | 000.00379737 | -19.49883745 | 9.27  |   21.90
3    | 00 00 01.20 | +38 51 33.4 | 000.00500795 | +38.85928608 | 6.61  |    2.81
4    | 00 00 02.01 | -51 53 36.8 | 000.00838170 | -51.89354612 | 8.06  |    7.75
5    | 00 00 02.39 | -40 35 28.4 | 000.00996534 | -40.59122440 | 8.55  |    2.87
6    | 00 00 04.35 | +03 56 47.4 | 000.01814144 | +03.94648893 | 12.31 |   18.80
7    | 00 00 05.41 | +20 02 11.8 | 000.02254891 | +20.03660216 | 9.64  |   17.74
8    | 00 00 06.55 | +25 53 11.3 | 000.02729160 | +25.88647445 | 9.05  |    5.17
9    | 00 00 08.48 | +36 35 09.4 | 000.03534189 | +36.58593777 | 8.59  |    4.81
10   | 00 00 08.70 | -50 52 01.5 | 000.03625309 | -50.86707360 | 8.59  |   10.76
... (118208 rows omitted)

# Accesing to columns

In [8]:
type(data.column(3))

numpy.ndarray

In [6]:
max(data.column('RAdeg'))

'359.97879195'

In [7]:
max(data.column('DEdeg'))

'-89.78245385'

In [21]:
dat.sort(1)

NameError: name 'dat' is not defined

In [9]:
float(data.column(3)[0])

9.1

In [10]:
float(data.column(4)[0])

3.54

In [32]:
3.4/10

0.33999999999999997

In [10]:
data.where('HIP', are.equal_to(85665))

HIP   | RAhms       | DEdms       | RAdeg        | DEdeg        | Vmag | Plx
85665 | 17 30 22.71 | +05 32 56.8 | 262.59462845 | +05.54912350 | 9.33 |  100.17

In [14]:
data.where('HIP', are.equal_to(85665)).column('RAhms')

array(['17 30 22.71'], dtype='<U11')

# Testing functions

In [33]:
log(3.4/10)

2.1877616239495525

In [34]:
(math.log(3.54/1000, 10) * 5) + 5 + 9.1

1.8450163101289405

In [50]:
calculate_abs_mag(9.1, 3.54)

1.8450163101289405

In [51]:
calculate_distance(9.1, calculate_abs_mag(9.1, 3.54)), "pc"

(282.48587570621453, 'pc')

In [52]:
calculate_distance(11.01, 15.44)

1.3001695780332905

# Error in 421 element
## The element 421 doesn't has RAdeg, DEdeg, neither Plx

In [12]:
abs_mag = []

for i in range(0, 421, 1):
    abs_mag.append(calculate_abs_mag(float(data.column(3)[i]), float(data.column(4)[i])))
    
abs_mag[:5]

ValueError: math domain error

# Visualize the error

In [39]:
data.take([419,420,421])

HIP  | RAdeg        | DEdeg        | Vmag | Plx
420  | 001.28166779 | -52.15142338 | 7.53 |   23.90
421  |              |              | 8.83 |
422  | 001.28675856 | +67.84002075 | 7.41 |    2.53

# 263 elements are in the same situation

In [13]:
data.where(4, data.take(420).column(4))

HIP  | RAdeg        | DEdeg        | Vmag  | Plx
421  |              |              | 8.83  |
1338 |              |              | 9.2   |
1902 |              |              | 8.88  |
2189 |              |              | 7.82  |
3158 |              |              | 9.59  |
3482 |              |              | 8.96  |
3856 |              |              | 13.26 |
5502 |              |              | 11.57 |
6132 |              |              | 11.14 |
7635 |              |              | 11.24 |
... (253 rows omitted)

In [14]:
data.where(1, data.take(420).column(1))

HIP  | RAdeg        | DEdeg        | Vmag  | Plx
421  |              |              | 8.83  |
1338 |              |              | 9.2   |
1902 |              |              | 8.88  |
2189 |              |              | 7.82  |
3158 |              |              | 9.59  |
3482 |              |              | 8.96  |
3856 |              |              | 13.26 |
5502 |              |              | 11.57 |
6132 |              |              | 11.14 |
7635 |              |              | 11.24 |
... (253 rows omitted)

# Asigning new table without those elements
## 117,955 stars

In [15]:
data_a = data.where(1, are.not_equal_to(data.take(420).column(1)))
data_a

HIP  | RAdeg        | DEdeg        | Vmag  | Plx
1    | 000.00091185 | +01.08901332 | 9.1   |    3.54
2    | 000.00379737 | -19.49883745 | 9.27  |   21.90
3    | 000.00500795 | +38.85928608 | 6.61  |    2.81
4    | 000.00838170 | -51.89354612 | 8.06  |    7.75
5    | 000.00996534 | -40.59122440 | 8.55  |    2.87
6    | 000.01814144 | +03.94648893 | 12.31 |   18.80
7    | 000.02254891 | +20.03660216 | 9.64  |   17.74
8    | 000.02729160 | +25.88647445 | 9.05  |    5.17
9    | 000.03534189 | +36.58593777 | 8.59  |    4.81
10   | 000.03625309 | -50.86707360 | 8.59  |   10.76
... (117945 rows omitted)

# Calculate MIN - MAX Vmag values

In [16]:
float_Vmag = []
for i in range(data_a.num_rows):
    float_Vmag.append(float(data_a.column(3)[i]))
    
type(float_Vmag[0])

float

In [17]:
min(float_Vmag)

-1.44

In [18]:
max(float_Vmag)

14.08

# Calculate Absolute Magnitude
### M = m + 5 + 5 log π”
#### La fórmula pide el Paralaje en arco de segundo. La matriz tiene el Plx en miliarco de segundo.

# Error cuando el Plx es negativo o cero

In [19]:
abs_mag = []

for i in range(0, 41, 1):
    """ Implementa la función calculate_abs_mag()
        enviando de parámetros los valores de las variables Vmag y Plx.
    """ 
    abs_mag.append(float(calculate_abs_mag(float(data_a.column(3)[i]), float(data_a.column(4)[i]))))
    
abs_mag[:5]

ValueError: math domain error

# Visualize the error

In [21]:
data_a.where(0, are.equal_to(40))

HIP  | RAdeg        | DEdeg        | Vmag  | Plx
40   | 000.12196971 | +67.21679125 | 10.61 |   -3.40

In [2]:
#calculate_abs_mag(10.61, -3.40)

In [3]:
#data_a.where(0, are.equal_to(979))

In [4]:
#calculate_abs_mag(8.68, 0)

# Parse Plx column to float to analize

In [25]:
plx = []

for i in range(0, len(data_a.column(4)), 1):
    plx.append(float(data_a.column(4)[i]))
    
plx[:5]

[3.54, 21.9, 2.81, 7.75, 2.87]

In [6]:
data_b = data_a.select(0, 1, 2, 3).with_columns(
    'Plx', plx
)
#data_b

# How many elements have negative  and zero value in Plx
## 4,196 elements have negative Plx
## 49 elements have zero in Plx

In [33]:
print(data_b.where(4, are.below(0))) # Below
print()
print(data_b.where(4, are.equal_to(0))) # Equal to

HIP  | RAdeg        | DEdeg        | Vmag  | Plx
40   | 000.12196971 | +67.21679125 | 10.61 | -3.4
53   | 000.14739023 | -29.26338247 | 10.96 | -1.76
59   | 000.17444749 | +55.72246267 | 9.09  | -0.06
147  | 000.46604367 | +21.02624872 | 8.49  | -0.13
165  | 000.51974463 | -22.32747055 | 10.16 | -0.59
209  | 000.66015960 | +66.10037725 | 7.2   | -0.69
251  | 000.77540550 | -25.26104885 | 8.65  | -0.53
252  | 000.77959051 | +29.48598254 | 10.3  | -0.95
312  | 000.98959785 | +61.10364174 | 8.59  | -0.56
338  | 001.06734897 | +66.34913841 | 10.66 | -1.21
... (4186 rows omitted)

HIP   | RAdeg        | DEdeg        | Vmag  | Plx
979   | 003.02528260 | -54.36533695 | 8.68  | 0
1466  | 004.57391863 | +61.72706050 | 7.63  | 0
6352  | 020.39363302 | -25.46668382 | 11.8  | 0
18895 | 060.75953667 | +34.62551691 | 10.09 | 0
24694 | 079.44322532 | -69.84923159 | 10.75 | 0
27376 | 086.97207852 | +28.78950093 |  9.01 | 0
30452 | 096.01621400 | +25.41700600 |  8.44 | 0
30977 | 097.52332845 | +09.02971927 |  6.57 | 0
32854 | 102.71778506 | -01.42922737 | 10.92 | 0
38180 | 117.36222436 | -76.01168198 | 11.64 | 0
... (39 rows omitted)

# Asigning new table without those elements
## 113,710 stars

In [37]:
data_c = data_b.where(4, are.above(0))
data_c

HIP  | RAdeg        | DEdeg        | Vmag  | Plx
1    | 000.00091185 | +01.08901332 | 9.1   | 3.54
2    | 000.00379737 | -19.49883745 | 9.27  | 21.9
3    | 000.00500795 | +38.85928608 | 6.61  | 2.81
4    | 000.00838170 | -51.89354612 | 8.06  | 7.75
5    | 000.00996534 | -40.59122440 | 8.55  | 2.87
6    | 000.01814144 | +03.94648893 | 12.31 | 18.8
7    | 000.02254891 | +20.03660216 | 9.64  | 17.74
8    | 000.02729160 | +25.88647445 | 9.05  | 5.17
9    | 000.03534189 | +36.58593777 | 8.59  | 4.81
10   | 000.03625309 | -50.86707360 | 8.59  | 10.76
... (113700 rows omitted)

# Calculate Absolute Magnitude

In [38]:
abs_mag = []

for i in range(0, data_c.num_rows, 1):
    """ Implementa la función calculate_abs_mag()
        enviando de parámetros los valores de las variables Vmag y Plx.
    """ 
    abs_mag.append(float(calculate_abs_mag(float(data_c.column(3)[i]), float(data_c.column(4)[i]))))
    
abs_mag[:5]

[1.8450163101289405,
 5.972220574200591,
 -1.1464684004745989,
 2.5065085125315534,
 0.8394094836699644]

# Calculate MIN - MAX abs_mag values

In [39]:
max(abs_mag) # Proxima Centauri

15.449014523417619

In [40]:
min(abs_mag)

-13.309999999999999

# Adding new abs_mag variable to new table

In [44]:
data_d = data_c.with_columns(
    'abs_mag', abs_mag
)
data_d.show(5)

# Converting astronomic coordinates
### From RA, DEC, R to X, Y, Z
### 500 pc/pixels of fixed distance

In [45]:
c = SkyCoord(ra=float(data_d.column(1)[0])*u.degree, dec=float(data_d.column(2)[0])*u.degree, distance=500*u.pc)
c.cartesian

<CartesianRepresentation (x, y, z) in pc
    (499.9096874, 0.00795596, 9.50286182)>

In [46]:
c.cartesian.x

In [47]:
c.cartesian.y

# Parse a float

In [48]:
float(str(c.cartesian.z)[:-3])

9.502861822975648

# Important!
## The next code takes its time to load

In [49]:
x = []
y = []
z = []
dist = []

for i in range(data_d.num_rows):
    d  = SkyCoord(ra=float(data_d.column(1)[i])*u.degree, dec=float(data_d.column(2)[i])*u.degree, distance=500*u.pc).cartesian
    x.append(str(d.x)[:-3])
    y.append(str(d.y)[:-3])
    z.append(str(d.z)[:-3])
    dist.append(500)

In [50]:
len(x)

113710

In [51]:
x[:5]

['499.9096873975101',
 '471.3241309387688',
 '389.3445872638265',
 '308.5622530645123',
 '379.68548077415886']

In [52]:
type(y[0])

str

In [53]:
float(x[0])

499.9096873975101

# Adding new variables to new table

In [54]:
hipparcos_catalogue = data_d.with_columns(
    'dist (pc)', dist,
    'x', x,
    'y', y,
    'z', z    
)
hipparcos_catalogue

HIP  | RAdeg        | DEdeg        | Vmag  | Plx   | abs_mag  | dist (pc) | x                  | y                    | z
1    | 000.00091185 | +01.08901332 | 9.1   | 3.54  | 1.84502  | 500       | 499.9096873975101  | 0.007955955087194905 | 9.502861822975648
2    | 000.00379737 | -19.49883745 | 9.27  | 21.9  | 5.97222  | 500       | 471.3241309387688  | 0.031237765380518073 | -166.89386633131963
3    | 000.00500795 | +38.85928608 | 6.61  | 2.81  | -1.14647 | 500       | 389.3445872638265  | 0.034030747942053956 | 313.70494291653864
4    | 000.00838170 | -51.89354612 | 8.06  | 7.75  | 2.50651  | 500       | 308.5622530645123  | 0.04513903601519708  | -393.43275657502045
5    | 000.00996534 | -40.59122440 | 8.55  | 2.87  | 0.839409 | 500       | 379.68548077415886 | 0.06603793471851585  | -325.32895863769494
6    | 000.01814144 | +03.94648893 | 12.31 | 18.8  | 8.68079  | 500       | 498.81435692203354 | 0.1579385271750702   | 34.41238707035282
7    | 000.02254891 | +20.03660216 | 9.64  | 17.74 | 5.88477  | 500       | 469.73693209341593 | 0.18486625790435152  | 171.31018782294365
8    | 000.02729160 | +25.88647445 | 9.05  | 5.17  | 2.61745  | 500       | 449.830382804242   | 0.2142669478998917   | 218.2947108746891
9    | 000.03534189 | +36.58593777 | 8.59  | 4.81  | 2.00073  | 500       | 401.4818155221117  | 0.24764700090192404  | 298.0139098700462
10   | 000.03625309 | -50.86707360 | 8.59  | 10.76 | 3.74906  | 500       | 315.56077534675126 | 0.19966662139915967  | -387.84192294773584
... (113700 rows omitted)

# Calculate real distance to 113,710 stars
### d = 10**((m - M + 5) / 5)

In [55]:
# Aplica la función calculate_distance enviando los valores de las variables Vmag y abs_mag
distance = data_d.apply(calculate_distance, 'Vmag', 'abs_mag')
distance[:5]

array([282.48587571,  45.66210046, 355.87188612, 129.03225806,
       348.43205575])

# Overwriting dist (pc) variable with real distance

In [56]:
hip_cat = hipparcos_catalogue.with_columns(
    'dist (pc)', distance
)
hip_cat

HIP  | RAdeg        | DEdeg        | Vmag  | Plx   | abs_mag  | dist (pc) | x                  | y                    | z
1    | 000.00091185 | +01.08901332 | 9.1   | 3.54  | 1.84502  | 282.486   | 499.9096873975101  | 0.007955955087194905 | 9.502861822975648
2    | 000.00379737 | -19.49883745 | 9.27  | 21.9  | 5.97222  | 45.6621   | 471.3241309387688  | 0.031237765380518073 | -166.89386633131963
3    | 000.00500795 | +38.85928608 | 6.61  | 2.81  | -1.14647 | 355.872   | 389.3445872638265  | 0.034030747942053956 | 313.70494291653864
4    | 000.00838170 | -51.89354612 | 8.06  | 7.75  | 2.50651  | 129.032   | 308.5622530645123  | 0.04513903601519708  | -393.43275657502045
5    | 000.00996534 | -40.59122440 | 8.55  | 2.87  | 0.839409 | 348.432   | 379.68548077415886 | 0.06603793471851585  | -325.32895863769494
6    | 000.01814144 | +03.94648893 | 12.31 | 18.8  | 8.68079  | 53.1915   | 498.81435692203354 | 0.1579385271750702   | 34.41238707035282
7    | 000.02254891 | +20.03660216 | 9.64  | 17.74 | 5.88477  | 56.3698   | 469.73693209341593 | 0.18486625790435152  | 171.31018782294365
8    | 000.02729160 | +25.88647445 | 9.05  | 5.17  | 2.61745  | 193.424   | 449.830382804242   | 0.2142669478998917   | 218.2947108746891
9    | 000.03534189 | +36.58593777 | 8.59  | 4.81  | 2.00073  | 207.9     | 401.4818155221117  | 0.24764700090192404  | 298.0139098700462
10   | 000.03625309 | -50.86707360 | 8.59  | 10.76 | 3.74906  | 92.9368   | 315.56077534675126 | 0.19966662139915967  | -387.84192294773584
... (113700 rows omitted)

# Exporting to CSV

In [174]:
#hip_cat.to_csv('hip_cat.csv')

# Reading hip_cat Table

In [57]:
hip_cat = Table.read_table("hip_cat.csv", sep=',')
hip_cat.show(5)

# Converting astronomic coordinate with real distance
### From RA, DEC, R to X, Y, Z

In [58]:
f = SkyCoord(ra=float(hip_cat.column(1)[0])*u.degree, dec=float(hip_cat.column(2)[0])*u.degree, distance=float(hip_cat.column(6)[0])*u.pc)
f.cartesian

<CartesianRepresentation (x, y, z) in pc
    (282.43485164, 0.00449489, 5.36884849)>

In [59]:
float(str(f.cartesian.z)[:-3])

5.368848487556859

# Important!
## The next code takes its time to load

In [60]:
x = []
y = []
z = []
dist = []

for i in range(hip_cat.num_rows):
    e  = SkyCoord(ra=float(hip_cat.column(1)[i])*u.degree, dec=float(hip_cat.column(2)[i])*u.degree, distance=float(hip_cat.column(6)[i])*u.pc).cartesian
    x.append(str(e.x)[:-3])
    y.append(str(e.y)[:-3])
    z.append(str(e.z)[:-3])
    
len(x)

113710

In [61]:
x[:5]

['282.43485163701115',
 '43.0432996291113',
 '277.11358524115735',
 '79.62896853277731',
 '264.5891852084727']

# Adding new variables to new Table

In [62]:
hip_cat_2 = hip_cat.with_columns(
    'x', x,
    'y', y,
    'z', z    
)
hip_cat_2

HIP  | RAdeg      | DEdeg    | Vmag  | Plx   | abs_mag  | dist (pc) | x                  | y                    | z
1    | 0.00091185 | 1.08901  | 9.1   | 3.54  | 1.84502  | 282.486   | 282.43485163701115 | 0.00449488987977113  | 5.368848487556859
2    | 0.00379737 | -19.4988 | 9.27  | 21.9  | 5.97222  | 45.6621   | 43.0432996291113   | 0.002852763961691148 | -15.24144898002919
3    | 0.00500795 | 38.8593  | 6.61  | 2.81  | -1.14647 | 355.872   | 277.11358524115735 | 0.024221172912493896 | 223.27753944237602
4    | 0.0083817  | -51.8935 | 8.06  | 7.75  | 2.50651  | 129.032   | 79.62896853277731  | 0.011648783487792786 | -101.53103395484392
5    | 0.00996534 | -40.5912 | 8.55  | 2.87  | 0.839409 | 348.432   | 264.5891852084727  | 0.046019466702798446 | -226.7100757057105
6    | 0.0181414  | 3.94649  | 12.31 | 18.8  | 8.68079  | 53.1915   | 53.065357119365245 | 0.01680197097607129  | 3.660892241526894
7    | 0.0225489  | 20.0366  | 9.64  | 17.74 | 5.88477  | 56.3698   | 52.957940484037884 | 0.02084174271751427  | 19.313437184097374
8    | 0.0272916  | 25.8865  | 9.05  | 5.17  | 2.61745  | 193.424   | 174.01562197456175 | 0.08288856785295619  | 84.44669666332267
9    | 0.0353419  | 36.5859  | 8.59  | 4.81  | 2.00073  | 207.9     | 166.93630583039982 | 0.10297172594674592  | 123.91430763827279
10   | 0.0362531  | -50.8671 | 8.59  | 10.76 | 3.74906  | 92.9368   | 58.65441920943329  | 0.037112754906906985 | -72.0895767560847
... (113700 rows omitted)

# Exporting to CSV

In [25]:
#hip_cat_2.to_csv('hip_cat_2.csv')

# Manual operations

In [153]:
772.33/1000

0.7723300000000001

In [140]:
math.log(0.7723300000000001, 10)

-0.11219709531647619

In [141]:
-0.11219709531647619 * 5

-0.560985476582381

In [142]:
-0.560985476582381 + 5

4.439014523417619

In [143]:
4.439014523417619 + 11.01

15.449014523417619

# Automatize operations

In [144]:
calculate_abs_mag(11.01, 772.33)

15.449014523417619

# Manual Operation

In [145]:
11.01 - 15.44

-4.43

In [146]:
-4.43 + 5

0.5700000000000003

In [147]:
0.5700000000000003 / 5

0.11400000000000006

In [148]:
10**0.11400000000000006

1.3001695780332905

# Automatize Operation

In [149]:
calculate_distance(11.01, 15.44)

1.3001695780332905

# Calculate real distance dividing one between Plx

In [9]:
1/0.77233

1.2947833180117307

In [3]:
hip_cat_2

NameError: name 'hip_cat_2' is not defined